{% set name = "gvproxy" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containers/gvisor-tap-vsock/archive/v{{ version }}.tar.gz
  sha256: d635bc55dbb97cf2a469427fb84b7a90f37540f14b090c21356cce2e549b46e0

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-cgo') }}
    - go-licenses

test:
  commands:
    - gvproxy --help

about:
  home: https://github.com/containers/gvisor-tap-vsock
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files_gvproxy/
    - license-files_win-sshproxy/  # [win]
    - license-files_qemu-wrapper/  # [not win]
    - license-files_vm/  # [linux]
  summary: A new network stack based on gVisor
  dev_url: https://github.com/containers/gvisor-tap-vsock

extra:
  recipe-maintainers:
    - danielnachun
