context:
  version: "0.8.8"

package:
  name: gvproxy
  version: ${{ version }}

source:
  url: https://github.com/containers/gvisor-tap-vsock/archive/v${{ version }}.tar.gz
  sha256: 4f7c4885225d71b21f6b547b94d92fc6da4a4fef9d382fdd19c8ea67f67be839

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('go-cgo') }}
    - go-licenses

tests:
  - script:
      - gvproxy --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files_gvproxy/
    - if: win
      then: license-files_win-sshproxy/
      else: license-files_qemu-wrapper/
    - if: linux
      then: license-files_vm/
  summary: A new network stack based on gVisor
  homepage: https://github.com/containers/gvisor-tap-vsock
  repository: https://github.com/containers/gvisor-tap-vsock

extra:
  recipe-maintainers:
    - danielnachun
