context:
  version: "0.8.2"

package:
  name: gvproxy
  version: ${{ version }}

source:
  url: https://github.com/containers/gvisor-tap-vsock/archive/v${{ version }}.tar.gz
  sha256: 57bf983cc636d107cd86ecf3a147674cf2f2c18d7a5a92a9b39da842547bbc51

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('go-cgo') }}
    - go-licenses

tests:
  - script:
      - gvproxy --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files_gvproxy/
    - if: win
      then: license-files_win-sshproxy/
    - if: not win
      then: license-files_qemu-wrapper/
    - if: linux
      then: license-files_vm/
  summary: A new network stack based on gVisor
  homepage: https://github.com/containers/gvisor-tap-vsock
  repository: https://github.com/containers/gvisor-tap-vsock

extra:
  recipe-maintainers:
    - danielnachun
